// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxuhdhtfknvwlqkipjmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4dWhkaHRma252d2xxa2lwam12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2ODI1OTQsImV4cCI6MjA2MzI1ODU5NH0.eLk_bYHlB-Qb0sdRrmRUOR8N99WoHibaeKYl7EuHbPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);